title: 모조ㆍ로그
description: 살아가면서 나누고 싶거나 기억하고 싶은 것들의 저장소.
images:

license:
  title_of_work: 이 웹사이트
  link_to_work: https://mozo.kr
  createor_of_work: "@mozodev"
  link_to_creator_profile: https://github.com/mozodev
  year_of_creation: 2021

featuredImages:
  - image1.png
  - image2.jpg

themeNoPipe: true
